### ISSUE TITLE
sever-side fetch events

### ISSUE THREAD

**Issue by logonoff** [utmgdsc/website#174]
**Is your feature request related to a problem? Please describe.**
A current issue with this page is that the events page does not work when JS is turned off, which is bad for SEO. 

a solution is to use [Next.js' built in server-side data fetching](https://nextjs.org/docs/app/building-your-application/data-fetching/fetching-caching-and-revalidating), which would also eliminate the need for the usage of localStorage in the client.

**Comment by daniyalb** [comment]
I'd like to work on this issue. I read through the Next.js docs and saw that the [cache is automatically checked whenever a fetch request is made](https://nextjs.org/docs/app/building-your-application/caching#data-cache), so I'm thinking the only thing that needs to be done is to remove the calls to getDescriptionFromStorage and useLocalStorage in EventList.jsx

**Comment by logonoff** [comment]
assigned! i've already [started working on some of it](https://github.com/utmgdsc/website/tree/server-event-list) -- please take a look at it for inspiration or to base off of! the deploy preview is at https://github.com/utmgdsc/website/pull/192
