### ISSUE TITLE
migrate to next: image optimization

### ISSUE THREAD

**Issue by logonoff** [utmgdsc/website#7]
**Is your feature request related to a problem? Please describe.**

Fix the image optimization problem, atm the images are sent uncompressed and take up lots of bandwidth

**Describe the solution you'd like**

One solution is to migrate from `create-react-app` to next.js. It will also improve page loads and SEO which is a nice bonus, especially since most of our content is static, we want to have next.js SSR 

**Describe alternatives you've considered**

gatsby, create-react-app SSR plugin (sucks)

**Additional context**

**Comment by maddy020** [comment]
Hey @logonoff 
I would like to work on this issue
Please assign it to me
