### ISSUE TITLE
rename Twitter to "X"

### ISSUE THREAD

**Issue by logonoff** [utmgdsc/website#86]
**Describe the bug**
Twitter is now "X". Need to change the icon for Twitter to an X.

**To Reproduce**
1. Go to gdscutm.com
2. Observe the Twitter bird flying strong

**Expected behavior**
There should be an X

**Screenshots**
![image](https://github.com/utmgdsc/website/assets/18614559/e25dfc41-a763-4499-a141-31e0b8ab8cb4)

**Desktop (please complete the following information):**
 - OS: Windows 11 22H2
 - Browser Edge
 - Version 115.0.1901.188 (Official build) (64-bit)

**Additional context**
Maybe remove the icon altogether since it isn't maintained

**Comment by michaelmuthomi** [comment]
Hey, interested in taking on this issue if available.

**Comment by logonoff** [comment]
to update the icon you may want to also send a PR to https://github.com/mui/material-ui/tree/master/packages/mui-icons-material/custom to update `Twitter.jsx`..

**Comment by michaelmuthomi** [comment]
Sure. How about changing the icon to an svg from iconfinder

**Comment by logonoff** [comment]
i'd prefer you change the MUI icon directly (since you would also get a contribution to MUI) however if you insist use the SVG from https://about.twitter.com/en/who-we-are/brand-toolkit
